# Generated by Django 2.2.1 on 2019-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_pk', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_id', models.BigIntegerField(unique=True, verbose_name='Account ID')),
                ('account_name', models.CharField(max_length=100, unique=True, verbose_name='Account Name')),
                ('operator_account_id', models.BigIntegerField(unique=True, verbose_name='Account ID')),
            ],
        ),
        migrations.CreateModel(
            name='APN',
            fields=[
                ('apn_pk', models.BigAutoField(primary_key=True, serialize=False)),
                ('apn_name', models.CharField(max_length=100, unique=True, verbose_name='APN Name')),
                ('operator_account_id', models.ManyToManyField(to='article.Account')),
            ],
        ),
    ]
