# Generated by Django 2.2.1 on 2019-05-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_pk',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='apn',
            old_name='apn_pk',
            new_name='id',
        ),
    ]
