# Generated by Django 2.2.1 on 2019-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190526_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarwanAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marwan_account_number', models.BigIntegerField(unique=True, verbose_name='Access Link Account Number')),
                ('host_name_1', models.CharField(max_length=100, verbose_name='First Host Name')),
                ('host_name_2', models.CharField(max_length=100, verbose_name='Second Host Name')),
                ('apn_name', models.ManyToManyField(to='article.APN')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLinkAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_link_account_number', models.BigIntegerField(unique=True, verbose_name='Access Link Account Number')),
                ('apn_name', models.ManyToManyField(to='article.APN')),
            ],
        ),
    ]
