# Generated by Django 2.2.1 on 2019-05-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_accesslinkaccount_marwanaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslinkaccount',
            old_name='apn_name',
            new_name='apn',
        ),
        migrations.RenameField(
            model_name='apn',
            old_name='operator_account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='marwanaccount',
            old_name='apn_name',
            new_name='apn',
        ),
    ]
