# Generated by Django 2.2.1 on 2019-05-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190526_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iccid', models.CharField(max_length=50, verbose_name='ICCID')),
                ('apn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.APN')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('project', models.CharField(max_length=50, verbose_name='Project')),
                ('imie', models.CharField(max_length=50, verbose_name='IMIE')),
                ('sim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Gateway', to='article.SIM')),
            ],
        ),
    ]
