# Generated by Django 2.2.1 on 2019-05-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_gateway_sim'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accesslinkaccount',
            table='access_link_account_tb',
        ),
        migrations.AlterModelTable(
            name='account',
            table='account_tb',
        ),
        migrations.AlterModelTable(
            name='apn',
            table='apn_tb',
        ),
        migrations.AlterModelTable(
            name='gateway',
            table='gateway_tb',
        ),
        migrations.AlterModelTable(
            name='marwanaccount',
            table='marwan_account_tb',
        ),
        migrations.AlterModelTable(
            name='sim',
            table='sim_tb',
        ),
    ]
