# Generated by Django 2.2.1 on 2019-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190526_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='imie',
            field=models.CharField(max_length=50, unique=True, verbose_name='IMIE'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='serial',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='iccid',
            field=models.CharField(max_length=50, unique=True, verbose_name='ICCID'),
        ),
    ]
